- name: install pkgs
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - nfs-common
    - sssd
    - heimdal-clients
    - msktutil
    - htop
    - vim
    - fish
    - python3-pexpect

- name: add ad address into to hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ ad_server_ip }} {{ ad_server_name }} {{ ad_server_name }}.{{ ad_domain }}"
    create: yes

- name: apply template krb5.conf
  template:
    src: krb5.conf.j2
    dest: /etc/krb5.conf
    owner: root
    group: root
    backup: yes

- name: apply template sssd.conf
  vars:
    hostname: "{{ ansible_hostname }}"
  template:
    src: sssd.conf.j2
    dest: /etc/sssd/sssd.conf
    owner: root
    group: root
    mode: 0600
    backup: yes

- name: run msktutil gen keytab
  shell: "msktutil update --verbose --use-service-account --account-name {{ ad_user }} --old-account-password '{{ ad_user_password }}' --dont-change-password --keytab administrator.keytab"

- name: run kinit
  shell: kinit -k -t {{ ad_user }}.keytab {{ ad_user }}

- name: run klist
  shell: klist

- name: pause for 1 minutes to build app cache
  pause:
    minutes: 1

- name: run msktutil generate entry into ad with suffix
  shell: "msktutil -N -c -b 'CN=Computers' -s {{ ansible_hostname }}/{{ ansible_hostname }}.{{ ad_domain }} -k /etc/sssd/{{ ansible_hostname }}.keytab --computer-name {{ ansible_hostname }} --upn {{ ansible_hostname }}$ --server {{ ad_server_name }}.{{ ad_domain }} --user-creds-only"

- name: run msktutil generate entry into ad without suffix
  shell: "msktutil -N -c -b 'CN=Computers' -s {{ ansible_hostname }}/{{ ansible_hostname }} -k /etc/sssd/{{ ansible_hostname }}.keytab --computer-name {{ ansible_hostname }} --upn {{ ansible_hostname }}$ --server {{ ad_server_name }}.{{ ad_domain }} --user-creds-only"

- name: run kdestroy
  shell: kdestroy

- name: add pam_mkhomedir.so
  lineinfile:
    path: /etc/pam.d/common-session
    line: session required pam_mkhomedir.so skel=/etc/skel/ umask=0077
    insertafter: "^session required        pam_unix.so"
    create: yes

- name: enable and restart sssd
  systemd:
    name: sssd
    enabled: yes
    state: restarted

- name: add_user into sudo group
  shell: adduser {{ ad_user }} sudo
